config/routes.rb
Rails.application.routes.draw do
  resources :guests
  root to: 'guests#index'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
        
        before_save :set_fullname
        
        # Add class search method using fullname attribute
        def self.search(namesearch)
                if namesearch.present?
                        where('fullname LIKE ?', "%#{namesearch.downcase}%")
                end
        end

        # Sets fullname for each new guest.
        protected
                def set_fullname
                        self.fullname = [firstname, lastname].map(&:downcase).join(' ')
                end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.search(params[:namesearch])

  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:firstname, :lastname, :table)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :table %><br>
    <%= f.number_field :table %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<div class="container">
      <div class="row text-center" id="header">
              <div class="col-xs-12">
                      <h1>Welcome!</h1>
                      <h1>Thank You For Joining Us!</h1>
              </div>
      </div>
      <div class="row well well-lg text-center">
              <div class="col-sm-6 col-xs-12">
                      <%= image_tag("shikeeta.jpg", id:"crop") %>
              </div>
              <div class="col-sm-6 col-xs-12 text-center"> 
                      <h3>Find Your Table</h3>
                      <!-- Typeahead form for guest search -->
                      <form class="special-submit" data-remote="true">
                        <div id="bloodhound">
                        <input type='text' id='name-form'  class='form-control typeahead' value='<%= params[:namesearch] %>' name='namesearch' placeholder="Enter Name" autocomplete="off" >
                        <input type='submit' value='Submit' style='display:none' >
                        </div>
                      </form>
              </div>
              <div class="col-sm-6 col-xs-12 text-center results">
                        <h3 id="guest_name"></h3>
                        <h3>Your Table Number Is:</h3>
                        <h1 class="table_result" id="guest_table"></h1>
              </div>
      </div>
</div>      
               

app/views/guests/index.js.erb
<%if @guests%>
        $('#guest_name').text("<%= @guests.first.fullname.titleize + ',' %>");
        $('#guest_table').text("<%= @guests.first.table %>");
        $('#name-form').val("");
        $('.typeahead').typeahead('val', '');
        if ($('.results').css('display') == 'none') {
                $('.results').show();
        }
<%end%>

app/views/guests/new.html.erb
<h1>New guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @guest.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @guest.lastname %>
</p>

<p>
  <strong>Table:</strong>
  <%= @guest.table %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shikeeta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>